# Generated by Django 3.2.9 on 2021-11-23 12:48

import Malocclusion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malocclusion_Inference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Malocclusion_Image', models.ImageField(blank=True, upload_to=Malocclusion.models.upload_to)),
                ('Prediction', models.CharField(default='None', max_length=230)),
                ('Prediction_Angle_Class_R', models.IntegerField(choices=[(-1, 'Not-defined'), (1, 'CLASS-1'), (2, 'CLASS-2'), (3, 'CLASS-3')], default=-1, verbose_name='Prediction Angle class type right')),
                ('Prediction_Angle_Class_L', models.IntegerField(choices=[(-1, 'Not-defined'), (1, 'CLASS-1'), (2, 'CLASS-2'), (3, 'CLASS-3')], default=-1, verbose_name='Prediction Angle class type left')),
                ('Prediction_Class_R_Percent', models.CharField(default='None', max_length=230)),
                ('Prediction_Class_L_Percent', models.CharField(default='None', max_length=230)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
